# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

admm_genlasso <- function(A, b, D, lambda, reltol, abstol, maxiter, rho) {
    .Call('_augmentedADMM_admm_genlasso', PACKAGE = 'augmentedADMM', A, b, D, lambda, reltol, abstol, maxiter, rho)
}

admm_genlasso_with_M <- function(A, b, D, M, lambda, reltol, abstol, maxiter, rho) {
    .Call('_augmentedADMM_admm_genlasso_with_M', PACKAGE = 'augmentedADMM', A, b, D, M, lambda, reltol, abstol, maxiter, rho)
}

