# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

augADMM_genlasso <- function(A_mat, b_vec, D_mat, lambda, rho, alpha, abstol, reltol, maxiter) {
    .Call('_augADMM_augADMM_genlasso', PACKAGE = 'augADMM', A_mat, b_vec, D_mat, lambda, rho, alpha, abstol, reltol, maxiter)
}

